name: Deploy Tailscale
on: 
  push:
    branches:
      - master
      
jobs:
  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      
      - name: Ping to Server
        run: ping -c 5 ${{ secrets.SERVER_ADDR }}

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/multipurpose-discord-bot
            git pull origin master
            echo "API_KEY = /"${{secrets.DISCORD_API}}/"" > .env
            docker compose up            
