name: Deploy Tailscale
on: 
  push:
    branches:
      - master
      
jobs:
  deploy:  
    runs-on: ubuntu-lastest
    
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cd
      
      - name: Ping to Server
        run: ping -c 5 ${{ secrets.SERVER_ADDR }}
